project_id = "jgcfmzrwzkeotgtndeat"

[functions.extract-game-data]
verify_jwt = false

[functions.fetch-game-data]
verify_jwt = false

[functions.search-youtube-creators]
verify_jwt = false

[functions.ai-discovery-suggestions]
verify_jwt = true

[functions.ai-marketing-recommendations]
verify_jwt = true

[functions.ai-profile-suggestions]
verify_jwt = true
